name: studio_manager_web
description: Sistema de gestão para estúdios de tatuagem
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.0.0

  # Calendar
  table_calendar: ^3.0.9

  # Utils
  intl: ^0.18.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
